### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by kurtextrem** [d4rkr00t/whybundled#13]
```
((!stats.children[0].chunks || !stats.children[0].chunks[0].modules) &&
                                                                    ^

TypeError: Cannot read property 'modules' of undefined
    at vlidateStatsJson (C:\Users\admin\AppData\Roaming\npm\node_modules\whybundled\lib\validate.js:25:69)
    at defaultCommand (C:\Users\admin\AppData\Roaming\npm\node_modules\whybundled\commands\default.js:31:8)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\whybundled\cli.js:61:3)
```

stats.json: https://kurtextrem.de/assets/stats.json
webpack config: https://github.com/kurtextrem/Improved-for-Instagram/blob/master/webpack.config.js#L309

whybundled version: 1.2.0

**Comment by d4rkr00t** [comment]
Thanks for reporting this. I fixed a type error, but support for stats.json with deeply nested children is quite a WIP, and i wouldn't rely much on a report just yet :) 

Released as [v1.2.1](https://github.com/d4rkr00t/whybundled/releases/tag/v1.2.1)
