### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by humphreybc** [d4rkr00t/whybundled#22]
I'm trying to analyze [this stats.json file](https://github.com/d4rkr00t/whybundled/files/2300843/stats.json.zip) generated by [gatsby-plugin-webpack-bundle-analyzer](https://www.gatsbyjs.org/packages/gatsby-plugin-webpack-bundle-analyzer/) and I'm running into the following error:

```
humphreybc@Benjamins-MacBook-Pro:~/C/dovetail-website:master$ whybundled stats.json
/usr/local/lib/node_modules/whybundled/lib/analyze.js:233
    const clearName = getModuleName(module.name);
                                           ^
TypeError: Cannot read property 'name' of undefined
    at modules.map.module (/usr/local/lib/node_modules/whybundled/lib/analyze.js:233:44)
    at Array.map (<anonymous>)
    at pickFromModules (/usr/local/lib/node_modules/whybundled/lib/analyze.js:232:11)
    at analyze (/usr/local/lib/node_modules/whybundled/lib/analyze.js:332:19)
    at defaultCommand (/usr/local/lib/node_modules/whybundled/commands/default.js:39:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/whybundled/cli.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
```

**Comment by d4rkr00t** [comment]
Released as [v1.4.1](https://github.com/d4rkr00t/whybundled/releases/tag/v1.4.1)
