### ISSUE TITLE
Can't run with node v8

### ISSUE THREAD

**Issue by marklavrynenko-original** [d4rkr00t/whybundled#23]
I got following error
```
~/work/repo [master] $ whybundled 
/usr/local/lib/node_modules/whybundled/cli.js:66
      ...defaultReporter,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
because of object spread operator which in supported starting from nodejs v8.3.0
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility

At least specify which version of node is required in package.json

**Comment by d4rkr00t** [comment]
> At least specify which version of node is required in package.json
That doesn't sound nice :) 

Fixed in 291ef58
